filter:
    paths: [src/*]
    excluded_paths: [vendor/*, Tests/*]

before_commands:
    - 'composer install --dev --prefer-dist'

tools:
    php_changetracking: true
    php_analyzer: true
    php_sim: true
    php_mess_detector: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, Tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, Tests]
    php_cs_fixer:
        config: { level: psr2 }
    php_analyzer: true
    js_hint: true
    php_code_coverage:
        enabled: true

checks:
    php:
        code_rating: true
        duplication: true

build:
    tests:
        override:
            -
                command: 'bin/phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'
